FROM php:7.4-fpm

RUN apt-get update
RUN apt-get -yqq install curl \ 
    zip \
    unzip \
    nodejs \
    npm \
    libicu-dev \
    freetds-bin \
    freetds-dev \
    libxml2-dev 

# Pacotes que talvez sejam necessários
#    libicu-dev 
#    libonig-dev \
#    libpng-dev

RUN cp /usr/lib/x86_64-linux-gnu/libsybdb.so.5 /usr/lib/libsybdb.so

RUN docker-php-ext-install pdo_dblib \ 
    pdo_mysql \
    soap 
#    gd \ 
#    mbstring \
#    intl \
#    json \
#    simplexml \


# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/

COPY . .

RUN composer install --no-interaction --no-dev

RUN cp .env.example .env
RUN php artisan key:generate

#RUN php artisan migrate:fresh

CMD ["php","artisan","serve","--host=0.0.0.0:8000"]
